variable "bucket_name" {}
variable "bucket_acl" {}
variable "enable_bucket_versioning" {}
variable "encryption_algorithm" {}
variable "enable_lifecyle_rule" {}
variable "project_name" {}
variable "tags" {}
variable "glacier_transition_days" {}
variable "one_zone_ia_transition_days" {}
variable "expiration_days" {}